export const QUOTES = [
  "Let it happen, let it happen...",
  "Feels like we only go backwards...",
  "'Cause I'm a man, not a hero...",
  "They say people never change, but that's bullshit, they do",
  "I was gonna tell you all about it...",
  "I waited 'til the end of summer...",
  "I'm changing who I am...",
  "Just 'cause I don't regret it doesn't mean I won't think about it",
  "Why won't they talk to me?",
  "It might be time to face it",
  "All this running around, I can't fight it much longer",
  "There is no future I can see...",
  "Gotta be above it now",
  "Do you remember we were standing here a year ago?",
  "What have I done? I should have known she’d leave",
  "I can only think about you, what a way to do this",
  "One more year, now we're older",
  "Borderline, what's in the air?",
  "We'll be flying in my spaceship",
  "I know that I gotta be above it now",
  "You gotta be what you wanna be",
  "And I know that I gotta be above it now",
  "I never wanted them to know",
  "But I can't explain it any other, any other way",
  "I told myself I wouldn't care, but I could see us coming back",
  "Maybe I was ready all along",
  "If only there could be another way to do this",
  "Maybe you know what I mean when I say so long",
  "She remembers my name now",
  "Lost in yesterday, coulda been another one",
  "Breath deeper, just relax",
  "I'm just a man, woman",
  "It feels like I only go backwards baby",
  "Reality in motion",
  "Love/Paranoia, don't want to let you down",
  "Yes I'm changing, yes I'm gone",
  "Eventually, terrible things will happen",
  "Cause I'm a man, I'm human",
  "No choice but to follow, I feel like I never know",
  "All I do is think about you",
  "Is it true?",
